### ISSUE TITLE
Some Ideas

### ISSUE THREAD

**Issue by JanSharp** [ClaudeMetz/UntitledGuiGuide#2]
Looking great so far. It's very consitent and i would think also easy to follow.
For me personally, even when leanring something new, i feel like it's too verbose, but too verbose is most likely better than the opposite, increasing the chance of misunderstandings. (I could go into detail why i think it's better to be "too verbose" imo because i have lots of reasons, but i don't feel like it's necessary. Just know that it's not a bad thing.)

There are just a few ideas i had. Not sure how to share them, so i [pushed them to a separate branch in my fork](https://github.com/JanSharp/UntitledGuiGuide/commit/c72ff2a5974ba6126cf111b9584368fbf121c311).

**Comment by ClaudeMetz** [comment]
Thanks for the feedback! I was pretty verbose on purpose because explanations like these have a lot of room for ambiguity, and I don't want to give the wrong idea about things. It's definitely not for someone wanting to throw a quick GUI together, but for someone that wants to actually learn about the details of how they work. 

If you view it from that point of view, I think it's 'appropriately verbose', as I feel like I don't go on about some silly detail for three paragraphs. I just touch on a lot of things because there's a lot to explain, and the explanations themselves are pretty to the point. Feel free to tell me about spots where you think I am just waffling though ofc.

Regarding your ideas, I'll add the link. The second thing about the loop is a matter of coding preference I guess. I'll stew on it a bit, I think either way is fine, especially since it doesn't matter for the GUI stuff itself really.

Funny that you bring the tags thing up, I actually wanted to have another chapter that goes into exactly that, writing on_click handlers for those buttons. I decided to move it to advanced techniques for now, maybe I'll make it a chapter still, not sure. It'll definitely be mentioned though :)

Edit: I decided to make the tags thing into a chapter, and probably even append another chapter where I fix all the shortcuts I took in the tutorial to avoid hitting readers over the head with too much info at once.

EditEdit: I wrote the tags chapter, feel free to take a look. Still first draft again, obviously. I also think I'll want to move the tut over to the Github Wiki functionality, seems worth to try that out.

**Comment by JanSharp** [comment]
yea regarding the verbose thing, i agree. One of the reasons i said it's good the way it is currently was pretty close to what you just said.

Regarding the loop, agreed. It is also fine the way it is for the record.

And i very much like the tags section. It has all the important information in it 👍 . And i consider it to be good to be in the main tutorial, because chances are just soo high for someone to need them, but if they end up looking at other mods, they'd find people using the name for everything, just how you explained as well, which would make their life way harder for no reason :D

**Comment by ClaudeMetz** [comment]
Alright, seems we agree, appreciate the feedback. I'll get to work on some of the advanced sections, and after that prep it for 'release'. If anything else comes to mind, please feel free to let me know of course.
